#file: noinspection UndefinedAction,UndefinedParamsPresent
name: Promote Stage to Production

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_USE_OIDC: true
  TF_VAR_tf_shared_resource_group_name: ${{ secrets.TF_STATE_RESOURCE_GROUP_NAME }}
  TF_VAR_tf_shared_storage_account_name: ${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}
  TF_VAR_tf_shared_container_name: ${{ secrets.TF_STATE_CONTAINER_NAME }}
  TF_VAR_tf_shared_key: ${{ secrets.TF_STATE_KEY }}
  TF_VAR_mysql_admin_username: ${{ secrets.MYSQL_ADMIN_USERNAME }}
  TF_VAR_mysql_admin_password: ${{ secrets.MYSQL_ADMIN_PASSWORD }}

jobs:
  promote-to-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Get Terraform outputs
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_STATE_RG }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STATE_SA }}" \
          -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ secrets.TF_STATE_KEY }}"

        FUNCTION_APP_NAME=$(terraform output -raw function_app_name)
        RG_NAME=$(terraform output -raw function_app_resource_group_name)

        echo "FUNCTION_APP_NAME=$FUNCTION_APP_NAME" >> $GITHUB_ENV
        echo "RG_NAME=$RG_NAME" >> $GITHUB_ENV
        echo "Function app name: $FUNCTION_APP_NAME"
        echo "Resource group: $RG_NAME"

    - name: Swap deployment slots
      run: |
        echo "Swapping stage and production slots..."
        echo "Function app: ${{ env.FUNCTION_APP_NAME }}"
        echo "Resource group: ${{ env.RG_NAME }}"

        az functionapp deployment slot swap \
          --name "${{ env.FUNCTION_APP_NAME }}" \
          --resource-group "${{ env.RG_NAME }}" \
          --slot "stage" \
          --target-slot "production"

        echo "✅ Successfully swapped stage -> production"
